# Generated by Django 2.0 on 2018-10-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0029_auto_20181028_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
